### ISSUE TITLE
[Current TODO] Project TODO List

### ISSUE THREAD

**Issue by arctome** [arctome/worker-scaffold#21]
Next minor release may contain (v1.1.0) :

- [ ] Add proper ESLint rule
- [ ] Improve Jest coverage

**Comment by arctome** [comment]
v1.0.6

- [x] Change testkit from 'cloudworker' to 'miniflare'
- [x] Improve bundle size & type declaration
